version: '3'
services:

  db:
    image: postgres:16
    restart: always
    ports:
      - "5632:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=db
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/db.sql
      - api_data:/var/lib/postgresql/data      

volumes:
  api_data:
