#spring:
#  datasource:
#    hikari:
#      jdbc-url: jdbc:postgresql://localhost:5634/db
#      username: user
#      password: user
#      driver-class-name: org.postgresql.Driver

security:
  basic:
    enable: false

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5632/db
    password: user
    username: user